services:
  # Redis for Global Distributed Rate Limiting
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      # Ensures Redis is ready to accept commands before dependent services start
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  # The Core Router Service
  router:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      mock-a:
        condition: service_started
      mock-b:
        condition: service_started
    restart: always

  # Mock Provider A
  mock-a:
    build:
      context: .
      dockerfile: ./mock/Dockerfile
    container_name: mock-a
    expose:
      - "8080"
    restart: always

  # Mock Provider B
  mock-b:
    build:
      context: .
      dockerfile: ./mock/Dockerfile
    container_name: mock-b
    expose:
      - "8080"
    restart: always