services:
  router:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
      - mock-a
      - mock-b

  mock-a:
    build:
      context: .
      dockerfile: ./mock/Dockerfile
    container_name: mock-a
    expose:
      - "8080"

  mock-b:
    build:
      context: .
      dockerfile: ./mock/Dockerfile
    container_name: mock-b
    expose:
      - "8080"

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"